---
  - debug:
      msg: "Bonjour, je suis {{ inventory_hostname }} ! " 


  - name: launch an instance
    become: no
    nova_compute:
      name: "{{ inventory_hostname }}"
      state: present
      login_username: "{{ lookup('env', 'OS_USERNAME') }}"
      login_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      login_tenant_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      region_name: fr1
      # image_id: d48f697e-7bb7-4c4d-b1c0-76674ac2cf47 # "CentOS 6.5"
      image_id: 4a4fdbd8-68da-4026-83d0-d2492e19e40b # CB_G2R3_Cloud_03_20G
      flavor_id: 16
      # flavor_include: t1.cw.tiny
      # flavor_ram: 4096
      key_name: KP_BadCops-Dev_GLL
      meta: 
        titi: toto
      security_groups: SSH_Only
      # user_data: $HOME/BadCops/cloudwatt/user_data_file.yaml
      # user_data: "{{ lookup('file', '../cloudwatt/user_data_file.yaml') }}"
      user_data: "#cloud-config\nmanage_etc_hosts: true\nssh_authorized_keys:
  - ssh-rsa  AAAAB3NzaC1yc2EAAAABIwAAAQEAoXSjjmUlmvmzAGj9q8Jjf9qJq5/7RPxmGoHfyv4//xXueFjn+A1iPszbdm80XjtSs5/1zGTBc2nA9wwssqtlFW1UKiZ7XXeOfA7bzb+RUrqGVQN4H2nqSlhp9ytysqeyd/Xo5O0ViACQbuOhQ86h2aE8b7YLvv5vgQ4jXZcTAEI2ng2reIFkuwRbrQjaiTbR20J5a79eBcKQ9mM7ZMpokH9jaoP9RGFIfUJvexTlL8zESSCwlo5VuruUeHmSs5P2+Ye0jYtCJ+lz09s2+NWUqhytgrVgj/2I+867ey9ycKK7e1eXs0jusjo3Faauui7gNBa2lMKjNqmoAY95DUFrzQ== cloud@in-bad-dev1-gll-01"

# +--------------------------------------+-----------------+------+
# | ID                                   | Label           | CIDR |
# +--------------------------------------+-----------------+------+
# | c65b4845-fdae-4196-b68b-865ec32dbc84 | reseau_interne2 | -    |
# | 6ea98324-0f14-49f6-97c0-885d1b8dc517 | public          | -    |
# | da0612d8-f507-4dbb-912d-c20786ee184d | reseau_interne1 | -    |
# +--------------------------------------+-----------------+------+
      nics:
        - net-id: da0612d8-f507-4dbb-912d-c20786ee184d      

      # auto_floating_ip: yes
      # floating_ip_pools: public
#      floating_ips: 
#        - "84.39.36.39"
    register: instance
  
  # - debug: var=instance
  - debug: msg="Server {{ instance.info.name }} created with ip={{ instance.private_ip }} ip={{ instance.public_ip }}" 

#  - name: Wait for cluster SSH to become available
#    wait_for:
#      port: 22
#      host: "{{ instance.private_ip }}"
#      timeout: 180
#      state: started
#    register: result
     
      
  
