---
- name: create SG for tenant
  hosts: localhost
  roles:
    # - { name: tenant, ensure: present }
    - tenant_SG 

  tags: create
  # serial: 1
  tasks:
    # - debug: msg="[tenant-create] Play-book a destination de {{ play_hosts }}"
    # - debug: msg="[tenant-create] Groups et leur hosts= {{groups|to_nice_yaml}}! "
  # - debug: msg="[tenant-create] hosts= {{hostvars}}! "
  

# - hosts: just_created
  # # serial: 1
  # tasks:
    # - debug: msg="[tenant-create] je suis {{ inventory_hostname }} du groupe {{ group_names }}! "
    # - debug: var=hostvars["{{ inventory_hostname }}"]['ansible_default_ipv4']
    # # - debug: msg={{ ansible_ssh_host }}
    # - ping:
      # register: first_ping
    # # - name: rerun setup
      # # setup:
    # # - name: get hostname
      # # command: hostname
      # # register: hostname
    # # - debug: msg="{{ hostname.stdout }}"    
      
        